[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/hardebayho"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/hardebayho1"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/adebayo-jagunmolu-458021bb"
[[social]]
  name = "youtube"
  weight = 4
  url = "https://www.youtube.com/channel/UCSw8bGHBmbhXKigsl_dcXzw"
[[social]]
  name = "rss"
  weight = 5
  url = "index.xml"

# other supported social links
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"